### ISSUE TITLE
Use checksums to determine download worked, not (necessarily) to determine if download is needed?

### ISSUE THREAD

**Issue by rwv37** [glujan/drpg#118]
I could easily be misunderstanding, but it looks to me like "--use-checksums" is used to indicate that the checksum should be used as part of determining whether or not a download is required - and that seems to be the _only_ use of checksums. Am I correct about that?

If so, what I would really hope for instead is:

1. Whether a file should be downloaded or not is determined by (A) whether or not it already has been downloaded, (B) whether or not the timestamps indicate a new version is available, and (C) _optionally_ whether the checksums match.
2. If a file is to be downloaded, it is downloaded to a temporary directory, and its checksum is verified. If it matches, the file is moved to its permanent home. An option (a _different_ one) would let you to skip the checksum verification in this step.

As someone with an absurd number of files from dtrpg, I would almost never opt _for_ checksumming in (1), and I imagine _literally_ never opt _against_ checksumming in (2). I want to know the file was downloaded properly, always. I do _not_ want to have checksumming done on previously successfully downloaded data every single time I use the program.

This is one of my biggest complaints about the official dtrpg library client app - it takes an _amazing_ amount of time just to get one new file, because it first checks whether or not any single byte of hundreds of gigabytes of previously downloaded data have become corrupted since the last time it ran.

Is there a way to do this, or something like it? Thanks.

**Comment by glujan** [comment]
Hi! You got right how drpg uses checksums - just to check if a product needs to be downloaded or not. 

Having an option to verify the integrity of downloaded files sounds really helpful! Do you feel like submitting a PR for that?

**Comment by rwv37** [comment]
<stuck_in_the_1990s>"PR" = "pull request"?</stuck_in_the_1990s> If so, I'm sorry, no, I've got far too much on my plate at the moment, and only have a passing familiarity with python anyway.

Thanks for this project, by the way - I've been using it for the past few days, and it's a godsend. Fighting against DTRPG's official client has taken up an embarrassing amount of my life, and it seems like this one just... works. I wish I had thought to search for an alternative to the official one long ago.

**Comment by glujan** [comment]
I'll try to prepare it this month

**Comment by rwv37** [comment]
Thank you!

**Comment by glujan** [comment]
Just a heads up, I did not forget about it. DriveThruRPG deployed a CloudFlare captcha for downloading files, which is challenging from the drpg point of view.

**Comment by glujan** [comment]
> Just a heads up, I did not forget about it. DriveThruRPG deployed a CloudFlare captcha for downloading files, which is challenging from the drpg point of view.

This wasn't Captcha, DriveThruRPG moved to a new API version and switched off the old one.

This feature can be now implemented, as drpg 2024.12.19 supports the new API.

**Comment by rwv37** [comment]
Just to put some numbers to this speed issue I've been facing:

After I first tried 2024.12.19 (which, like I said in the other thread, worked great), I ran it again (so that it should have very little if anything to try to download) and kept track of stuff:

76,563 lines of output, of which:

* 76,558 matched ``grep "^Up to date: "``
* 2 matched ``grep "^Processing: "``
* 2 matched ``grep "^Could not download: "`` (for the same two files that were "processing")
* 1 was the final "Done!"

That took 57 minutes.

**Comment by glujan** [comment]
Wow, that's a massive library! Did it take this long with or without the `--use-checksums` parameter? 

I plan to do 3 things:
1. As you suggested, allow verifying downloads with the `--validate` parameter. I'm thinking of a shortcut. Is `-v` good, or will it be confusing, as it often is an alias to `--verbose` in other CLI apps? There is a draft Pull Request which adds `--validate` but it's still buggy for some downloads. If you're feeling adventurous, you may install it via `pip install --user git+//github.com/glujan/drpg.git@Use-checksums-to-validate-downloads`, delete a few files, and run drpg with `--validate`.
2. Allow the user to specify the number of threads. _I thought_ it was based on CPU cores, but no, it's hardcoded to 5 for some reason. It is installable in the same way. To use it, specify `--threads 12` or `-x 12`.
3. Benchmark the app. There may be some low-hanging fruit that can speed this up.

**Comment by rwv37** [comment]
That was without ``--use-checksums``. Honestly I forgot that that existed 😆 

(1) I'm trying it now with that parameter. I suspect it's going to be considerably slower - I'm doing a ``tail -f`` on the output file, and I can see it taking a fairly small amount of time after each individual "Up to date:" line, then after some number of them (presumably 100) pause considerably for a bit, whereas without ``--use-checksums``, it would just BLAM! output a bunch (again, 100, I assume) of "Up to date:" lines at once, then the pause again.

So I guess maybe a large part of the issue (in addition to checksumming) might simply be how long it takes DTRPG to decide on what 100 things it should tell us about, collect that info, and actually send back to the client? If so, and if it's (A) possible, (B) sensible, and (C) not a hassle, maybe it would be good another optional parameter to say something like "Just try the last _N_ pages"?

By "sensible", I mean, like, if it can reasonably be assumed that DTRPG usually adds the newest things to the end of the overall list, or (even better) does that but also moves the most recently updated things to the end, too. So, that way, users could just do "last couple of pages" when they've actually bought something, and "all pages" a lot less frequently.

For what it's worth, it's been running for about 24 minutes so far, at a rate of a bit over three per second, whereas without ``--use-checksums`` it was more like twenty per second. So I guess yeah, checksumming is the biggest contributor to the issue, but request/reply's contribution is considerable too.

Or... maybe caching and eventual decaching (on my end or DTRPG's end or both) might be responsible for some noticeable amount of the disparity?

(2) ``-v`` would be fine with me, though I don't really have a strong opinion on it one way or the other.

(3) I need sleep, so I'm going to attempt to get some after finishing up this comment. I will (try to) try the experimental branch you mention tomorrow.

(4) I'd be happy to run "real" benchmarks, but I don't really know how to do so. If you have any pointers, I'd love to hear them.

Thanks again!

**Comment by glujan** [comment]
(1) I'll see what the official client does regarding this.

(2) Thanks

(3) No need to rush it!

(4) I've run some benchmarks and most of the time is spent on I/O, naming HTTP requests to the API. I have a small library, especially compared to yours, but even if all my files are downloaded, drpg spends most of the time fetching the product list.

Currently, the product list is fetched on demand - drpg fetches 1 page, processes items, and only once all items from the first page are processed, it fetches a second page. For your account, DriveThruRPG API might be even slower. Fetching the next pages in the background might be worth it, so drpg does not need to wait to process items until they are fetched.

**Comment by rwv37** [comment]
Just checked on what happened overnight with this. Unfortunately, there was an error:

```
Unexpected error occurred, stopping!
Traceback (most recent call last):
  File "/home/bob/.local/bin/drpg", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/bob/.local/lib/python3.11/site-packages/drpg/cmd.py", line 33, in run
    DrpgSync(config).sync()
  File "/home/bob/.local/lib/python3.11/site-packages/drpg/sync.py", line 69, in sync
    pool.starmap(self._process_item, process_item_args)
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 478, in _map_async
    iterable = list(iterable)
               ^^^^^^^^^^^^^^
  File "/home/bob/.local/lib/python3.11/site-packages/drpg/sync.py", line 61, in <genexpr>
    process_item_args = (
    ^
  File "/home/bob/.local/lib/python3.11/site-packages/drpg/api.py", line 61, in customer_products
    while result := self._product_page(page, per_page):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bob/.local/lib/python3.11/site-packages/drpg/api.py", line 121, in _product_page
    ).json()
      ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Up to that point, there were 12,604 "Up to date: " lines, and nothing else. It happened about 36 minutes into the run, so about six items per second.

I'm guessing it was just some temporary issue, and I'm about to start it again.

**Comment by rwv37** [comment]
OK, I ran it again, and did not expect this: In a little more than six hours:

* 63,833 "Up to date"
* 12,729 "Processing"
* 9,699 "Could not download product"
* 1 "Done!"
* 0 other lines

I guess the addition of ``--use-checksums`` made it decide that a bunch of previously downloaded things that apparently were up-to-date based on their timestamps had to be downloaded again. It successfully downloaded about 3,000 of those, but not about 10,000 others.

FWIW, I now remember that an issue I often had with the official client was that it sometimes kept deciding that the same file needed to be downloaded due to the checksum again and again and again. Customer support wasn't terribly helpful. If I remember correctly, I eventually determined that for some products you would get a different file if you downloaded manually from the website or if you used the official client. The two files would seem the same from the human point of view, but would have different checksums and sometimes different filenames. And downloading manually was only a temporary solution if you ever wanted to use the official client again.

Or something like that, at least. It was a while back, and I'm a forgetful man. I will try to see if I can refresh my memory from old emails and/or support tickets, if they exist.

Meanwhile, I'll try again, and see what happens this time.

**Comment by glujan** [comment]
> 9,699 "Could not download product"

Retries very often help. Drpg is now overoptimistic in how reliable the API is. Having a retry strategy for the http client is on my to-do.

I played around with the idea with fetching next product pages in the background using stdlib's `threading` and `multiprocessing` libraries. Results are not so promising at the moment, but I have 1 more idea to try out. I'll post an update here once I have something meaningful in your use case.

Updating the code made me realize that one can safely use tens on threads - drpg is not running separate _processes_, but _threads_. Silly me!

**Comment by niclasmagnusson** [comment]
I noticed something peculiar. Not all, but some zip-files gets downloaded with file extension zip, but identified as a pdf (with the <code>file</code>-command). I can't unzip them, and not open them in a pdf-reader. 

Downloading the same files through the website makes them legit and unzippable zip-files.

**Comment by glujan** [comment]
> I noticed something peculiar. Not all, but some zip-files gets downloaded with file extension zip, but identified as a pdf (with the <code>file</code>-command). I can't unzip them, and not open them in a pdf-reader. 
> 
> Downloading the same files through the website makes them legit and unzippable zip-files.

Interesting! Does it work with the official client? Could you give me an example of such a product, that ideally is free or cheap, so I can add it to my account? Maybe drpg is missing a value in Accept header or something like that 🤔

**Comment by xmagnn** [comment]
I haven't tried the official client yet, but I'll do that when I come home. 

Here are three examples, all free or pwyw. It's not only that it identifies as pdf, I have seen them identify as jpg, png, txt, rtf and also rar.

Shadowdark RPG Quickstart
the zip identifies as PDF
https://www.drivethrurpg.com/en/product/413713/shadowdark-rpg-quickstart-set

Goblin Hideout
the zip identifies as JPEG
https://www.drivethrurpg.com/en/product/343766/goblin-hideout

Ukrainian Arms
the two zips identifies as PDF
https://www.drivethrurpg.com/en/product/403114/ukrainian-arms

I can give you more examples if you need.

**Comment by xmagnn** [comment]
I see I posted from the wrong github-account, but xmagnn is my workself and niclasmagnusson is my private self

**Comment by glujan** [comment]
> I can give you more examples if you need.

That should do, thanks!

**Comment by niclasmagnusson** [comment]
I have now tried this at home with both the client and the script. I took two zip-files that identified as pdf. In the client, I deleted the files from the client and updated. Those files were unzipped nice and correct. 

I deleted the same files from my script-directory and ran the script again. Both files identified as pdf and couldn't be unzipped.

This is the kind of error message I get:

Archive:  ShadowSun_-_Digital.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ShadowSun_-_Digital.zip or
        ShadowSun_-_Digital.zip.zip, and cannot find ShadowSun_-_Digital.zip.ZIP, period.

**Comment by rwv37** [comment]
Over the past few days, I've tried several times, but each time it has failed with a timeout error. It doesn't seem to happen on any particular file; just happens randomly, usually a couple hours in. I guess maybe their servers are struggling a little, perhaps due to their holiday sale. I'll keep trying.

Here's a typical example of the error:

```
Unexpected error occurred, stopping!
Traceback (most recent call last):
  File "/home/bob/.local/bin/drpg", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/bob/.local/lib/python3.11/site-packages/drpg/cmd.py", line 33, in run
    DrpgSync(config).sync()
  File "/home/bob/.local/lib/python3.11/site-packages/drpg/sync.py", line 69, in sync
    pool.starmap(self._process_item, process_item_args)
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bob/.local/lib/python3.11/site-packages/drpg/sync.py", line 37, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bob/.local/lib/python3.11/site-packages/drpg/sync.py", line 84, in _process_item
    url_data = self._api.file_task(product["orderProductId"], item["index"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bob/.local/lib/python3.11/site-packages/drpg/api.py", line 100, in file_task
    while (data := _parse_message(resp))["status"].startswith("Preparing"):
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/bob/.local/lib/python3.11/site-packages/drpg/api.py", line 77, in _parse_message
    message: FileTasksResponse = resp.json()
                                 ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by glujan** [comment]
> I haven't tried the official client yet, but I'll do that when I come home.
> 
> Here are three examples, all free or pwyw. It's not only that it identifies as pdf, I have seen them identify as jpg, png, txt, rtf and also rar.
> 
> Shadowdark RPG Quickstart the zip identifies as PDF https://www.drivethrurpg.com/en/product/413713/shadowdark-rpg-quickstart-set
> 
> Goblin Hideout the zip identifies as JPEG https://www.drivethrurpg.com/en/product/343766/goblin-hideout
> 
> Ukrainian Arms the two zips identifies as PDF https://www.drivethrurpg.com/en/product/403114/ukrainian-arms
> 
> I can give you more examples if you need.

@niclasmagnusson It's now fixed on the feature branch. Until it is released, you can install it with `pip install—-user git+//github.com/glujan/drpg.git@Use-checksums-to-validate-downloads`.

**Comment by palfrey** [comment]
Did this get solved with https://github.com/glujan/drpg/pull/145 going out in 2025.1.1?
